#!/usr/bin/env python3
"""Sit-pose fallback table generator (BUG-013).

Census of the 1.2 client (r208022) game_pak animation assets vs the game data
anim_actions table: for every sit-range anim id (25-224) and every race/gender
model folder, determine whether the client can actually play the animation.
Unplayable (anim, folder, gender) combos are remapped to the closest playable
sit anim of the same family; the result is emitted as SitPoseFallback.cs.

Run ON the aaemu box (192.168.0.165) where game_pak + compact.sqlite3 live:

    python3 Tools/sit-pose-census/sit-pose-census.py <game_pak> <compact.sqlite3> <out.cs>

Re-run whenever the client pak or game data changes; commit the regenerated
AAEmu.Game/Models/Game/Units/SitPoseFallback.cs together with any table change.
"""
import os
import sqlite3
import struct
import sys

from Crypto.Cipher import AES

KEY = bytes([0x32, 0x1F, 0x2A, 0xEE, 0xAA, 0x58, 0x4A, 0xB4, 0x9A, 0x6C, 0x9E, 0x09, 0xD5, 0x9E, 0x9C, 0x6F])
IV = b'\x00' * 16


def read_pak_index(path):
    size = os.path.getsize(path)
    with open(path, 'rb') as f:
        f.seek(-0x200, 2)
        hdr = AES.new(KEY, AES.MODE_CBC, IV).decrypt(f.read(0x200))
    if hdr[:4] != b'WIBO':
        raise RuntimeError('pak header not WIBO type: %r' % hdr[:16])
    total = struct.unpack_from('<I', hdr, 8)[0] + struct.unpack_from('<I', hdr, 12)[0]
    fat_start = size - 0x200 - total * 0x150
    fat_start -= fat_start % 0x200
    with open(path, 'rb') as f:
        f.seek(fat_start)
        fat = f.read(total * 0x150)
    entries = {}
    for i in range(total):
        blk = AES.new(KEY, AES.MODE_CBC, IV).decrypt(fat[i * 0x150:(i + 1) * 0x150])
        name = blk[:0x108].split(b'\x00')[0].decode('ascii', 'replace')
        off, sz, _ = struct.unpack_from('<qqq', blk, 0x108)
        entries[name] = (off, sz)
    return entries


FOLDERS = ['nuian', 'dwarf', 'hariharan', 'ferre', 'warborn']
GENDERS = ['male', 'female']
SIT_MIN, SIT_MAX = 25, 224

# Fallback preference per pose family: first candidate that is playable for the
# (folder, gender) wins. Order = closeness of the substitute pose.
FALLBACKS = {
    'chair':  [141, 183, 105, 144, 87, 92, 93],
    'crouch': [224, 223, 75, 70, 25],
    'lean':   [141, 183, 105, 144],
    'ground': [155, 65, 141, 183],
    'sit':    [141, 183, 105, 144, 224, 223, 155, 26],
}


def family_of(name):
    n = name or ''
    if '_stn_' in n:
        return None  # stand poses — out of scope (BUG-013 keeps them untouched)
    if 'chair' in n:
        return 'chair'
    if 'crouch' in n:
        return 'crouch'
    if '_lean' in n:
        return 'lean'
    if '_gnd' in n or 'sidesleep' in n or 'drunken' in n:
        return 'ground'
    if '_sit' in n:
        return 'sit'
    return None


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    pak_path, db_path, out_path = sys.argv[1:4]

    print('reading pak index...')
    idx = read_pak_index(pak_path)
    print('pak entries:', len(idx))

    conn = sqlite3.connect(db_path)
    anim_name = dict(conn.execute('select id, anim_name from anim_actions'))

    def playable(aid, folder, gender):
        name = anim_name.get(aid)
        if not name:
            return True  # unknown anim: leave alone
        return ('game/animations/%s/%s/fist/%s.caf' % (folder, gender, name)) in idx

    entries = {}
    for aid in range(SIT_MIN, SIT_MAX + 1):
        name = anim_name.get(aid)
        if not name:
            continue
        fam = family_of(name)
        if fam is None:
            continue
        for folder in FOLDERS:
            for gender in GENDERS:
                if playable(aid, folder, gender):
                    continue
                fb = aid
                for cand in FALLBACKS.get(fam, []):
                    if cand != aid and playable(cand, folder, gender):
                        fb = cand
                        break
                if fb != aid:
                    entries[(aid, FOLDERS.index(folder) + 1, 1 if gender == 'male' else 2)] = fb

    print('sit-range anims:', sum(1 for a in range(SIT_MIN, SIT_MAX + 1) if anim_name.get(a)))
    print('remap entries:', len(entries))

    lines = [
        '// <auto-generated />',
        '// Sit-pose fallback table — generated from the 1.2 client (r208022) game_pak census',
        '// (see scorecard-explorations/npc-behavior.md, Recon B, sit-pose section, and bugs/013-npc-sit-pose.md).',
        '//',
        '// WHY: npc_postures.anim_action_id is sent verbatim, but the 1.2 client only ships the',
        '// fist_pos_sit_* .caf assets for a subset of race/gender models (and some sit anim ids,',
        '// e.g. 70/160, have no assets at all). The client cannot play a missing animation and',
        '// falls back to its default crouched pose ("knees in"). This table remaps an unplayable',
        '// sit-range anim id to the closest playable sit anim for the NPC\'s (race, gender), so the',
        '// client renders a correct sitting pose. Stand/walk poses are NOT in this table.',
        '//',
        '// Generation: Tools/sit-pose-census/sit-pose-census.py <game_pak> <compact.sqlite3> <out.cs>',
        '',
        'using AAEmu.Game.Models.Game.Char;',
        '',
        'namespace AAEmu.Game.Models.Game.Units;',
        '',
        '/// <summary>',
        '/// Remaps NPC sit-pose anim ids that the 1.2 client cannot play for the NPC\'s (race, gender)',
        '/// to the closest playable sit anim. Only the sit range (ids 25-224) is covered.',
        '/// </summary>',
        'public static class SitPoseFallback',
        '{',
        '    /// <summary>Anim action ids in the sit-pose range this table may remap (inclusive).</summary>',
        '    public const uint SitRangeMin = 25;',
        '    public const uint SitRangeMax = 224;',
        '',
        '    // (animActionId, folderIndex, gender) -> fallback animActionId',
        '    // folderIndex: 1=nuian, 2=dwarf, 3=hariharan(elf), 4=ferre, 5=warborn',
        '    private static readonly Dictionary<(uint, byte, byte), uint> Fallbacks = new()',
        '    {',
    ]
    for (aid, folder, gender), fb in sorted(entries.items()):
        lines.append('        [(%d, %d, %d)] = %d,' % (aid, folder, gender, fb))
    lines += [
        '    };',
        '',
        '    /// <summary>',
        '    /// Returns the playable fallback for <paramref name="animActionId"/> on the given race/gender,',
        '    /// or the original id when it is playable, out of the sit range, or has no known fallback.',
        '    /// </summary>',
        '    public static uint Resolve(uint animActionId, byte race, byte gender)',
        '    {',
        '        if (animActionId < SitRangeMin || animActionId > SitRangeMax)',
        '            return animActionId; // stand/walk/other poses pass through untouched',
        '',
        '        var folder = FolderIndex((Race)race);',
        '        if (folder == 0)',
        '            return animActionId;',
        '',
        '        return Fallbacks.GetValueOrDefault((animActionId, folder, gender), animActionId);',
        '    }',
        '',
        '    /// <summary>Maps a Race to the client animation folder index (1=nuian, 2=dwarf, 3=hariharan, 4=ferre, 5=warborn). 0 = unknown.</summary>',
        '    private static byte FolderIndex(Race race) => race switch',
        '    {',
        '        Race.Nuian or Race.Fairy or Race.Returned => 1,',
        '        Race.Dwarf => 2,',
        '        Race.Elf or Race.Hariharan => 3,',
        '        Race.Ferre => 4,',
        '        Race.Warborn => 5,',
        '        _ => 0,',
        '    };',
        '}',
    ]
    with open(out_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote', out_path, '-', len(entries), 'fallback entries')
    return 0


if __name__ == '__main__':
    sys.exit(main())
