using System.Text;
using AAEmu.Game.Models.Game.Bots;
using AAEmu.Game.Models.Game.Char;
using AAEmu.Game.Models.Game.Quests;
using AAEmu.Game.Models.Game.Quests.Static;
using AAEmu.UnitTests.Game.Quests.Scenario;

namespace AAEmu.UnitTests.Game.Quests.Playerbot;

/// <summary>
/// M2b playerbot repeatability pilot (Solzreed) — M6.0-lite slice.
///
/// The pilot drives REAL quest templates + REAL unit requirements (loaded from
/// the canonical compact.sqlite3 via QuestManager.Load) on headless bots
/// (ordinary Character records, no Connection). All mutations flow through
/// normal gameplay services: CharacterQuests.AddQuest (real gates), the
/// UnitEvents engine surface, QuestManager.DoReportEvents (the real packet
/// turn-in path). No bot-only quest state, no direct DB writes.
///
/// Test outcomes ARE the pilot outcomes: a FAIL here is a real finding
/// (engine/wiring/data defect) — every failure prints a repro trace with
/// quest id + stage, and the run wrapper (tools/playerbot-pilot/run-pilot.sh)
/// files a regression card per structured failure.
/// </summary>
[NotInParallel]
public class PlayerbotPilotTests
{
    #region Curriculum

    /// <summary>
    /// Solzreed golden route (character-cycle): the curated Nuian chain from
    /// Docs/wiki/Golden-Route-Solzreed.md — arrival quests -> village spine ->
    /// light fan -> shepherd arc -> mount chain, in route order. All 16 quests
    /// are census-PASS (T1 97/97) and their real QuestComponent gates are
    /// satisfiable in order (level gates + kind-31 completion chains + Nuian
    /// race on the mount chain; verified against canonical data 2026-08-06).
    /// </summary>
    private static readonly uint[] GoldenRoute =
        [251, 330, 252, 254, 255, 256, 257, 259, 260, 261, 265, 266, 354, 4292, 4294, 4295];

    #endregion

    #region Metrics model

    private sealed record CycleMetrics(
        int Bot, int Cycle, int PassedQuests, int TotalQuests, bool Passed,
        List<string> CleanupLeaks);

    private sealed class PilotRun
    {
        public List<CycleMetrics> Cycles { get; } = [];
        public List<string> Failures { get; } = [];
    }

    #endregion

    #region Helpers

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null && !Directory.Exists(Path.Combine(dir.FullName, ".git")))
            dir = dir.Parent;
        return dir?.FullName
               ?? throw new InvalidOperationException("Cannot locate repo root from " + AppContext.BaseDirectory);
    }

    private static QuestScenarioManifest LoadManifest(string tier, uint questId)
    {
        var path = Path.Combine(RepoRoot(), "AAEmu.UnitTests", "Game", "Quests", "Scenario", "Manifests", tier,
            $"{questId}.json");
        if (!File.Exists(path))
            throw new InvalidOperationException($"No manifest for quest {questId} at {path}");
        return QuestScenarioManifest.LoadFromFile(path);
    }

    private static (PlayerBotController Bot, HeadlessSession Session) NewBot(string name, byte level = 1)
    {
        var session = HeadlessSession.Create((uint)(name.GetHashCode() & 0xFFFF), name, level, Race.Nuian);
        return (new PlayerBotController(session.Character), session);
    }

    /// <summary>Emits the M2b metrics table to scorecard-explorations/m2b-pilot-metrics.md
    /// (deterministic header — no wall-clock churn, same discipline as the census).</summary>
    private static void EmitMetricsTable(PilotRun run, string curriculumLabel)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# M2b playerbot pilot metrics — " + curriculumLabel);
        sb.AppendLine();
        sb.AppendLine("> Generated by PlayerbotPilotTests (deterministic — no wall-clock).");
        sb.AppendLine("> Engine: real QuestManager.Load + real unit_reqs from canonical compact.sqlite3;");
        sb.AppendLine("> bots = ordinary Character records (no Connection); accept/turn-in via real engine paths.");
        sb.AppendLine();
        sb.AppendLine("| Metric | Definition | Green bar | Observed |");
        sb.AppendLine("|---|---|---|---|");
        sb.AppendLine();

        var grouped = run.Cycles.GroupBy(c => c.Bot).OrderBy(g => g.Key).ToList();
        foreach (var botGroup in grouped)
        {
            var attempts = botGroup.Count();
            var passed = botGroup.Count(c => c.Passed);
            sb.AppendLine($"| Bot {botGroup.Key} | cycles {passed}/{attempts} | 100% | {passed * 100.0 / attempts:0.0}% |");
        }

        // Mean cycles-to-complete over the last 5 cycles (deterministic drive -> 1.0).
        var last5 = run.Cycles.OrderByDescending(c => (c.Bot, c.Cycle)).Take(Math.Min(5 * grouped.Count, run.Cycles.Count));
        var meanCtc = last5.Any() ? last5.Average(c => c.Passed ? 1 : 0) : double.NaN;
        sb.AppendLine();
        sb.AppendLine($"| Mean cycles-to-complete | avg cycles to first full pass (last 5 cycles) | stable ±1 | {meanCtc:0.00} |");
        sb.AppendLine();

        var leakCount = run.Cycles.Sum(c => c.CleanupLeaks.Count);
        sb.AppendLine($"| State-cleanup | leaks over the run (ActiveQuests, completed-flag dupes, orphaned component state, reward totals) | 0 leaks | {leakCount} |");
        sb.AppendLine();
        sb.AppendLine("## Per-cycle detail");
        sb.AppendLine();
        sb.AppendLine("| Bot | Cycle | Quests | Passed | Cleanup leaks |");
        sb.AppendLine("|---|---|---|---|---|");
        foreach (var c in run.Cycles.OrderBy(c => c.Bot).ThenBy(c => c.Cycle))
        {
            var leaks = c.CleanupLeaks.Count == 0 ? "none" : string.Join("; ", c.CleanupLeaks);
            sb.AppendLine($"| {c.Bot} | {c.Cycle} | {c.TotalQuests} | {c.PassedQuests} | {leaks} |");
        }

        if (run.Failures.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("## Failures (drift — every entry is a regression card)");
            sb.AppendLine();
            foreach (var f in run.Failures)
                sb.AppendLine("- " + f.Replace("\n", " "));
        }

        var outPath = Path.Combine(RepoRoot(), "scorecard-explorations", "m2b-pilot-metrics.md");
        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine("M2b metrics table written to " + outPath);
    }

    #endregion

    #region Empirical re-accept gate (required work item 2)

    /// <summary>
    /// Gate question: does the engine re-accept a completed quest when
    /// REPEATABLE='f' (cat-34 daily board)?
    /// Answer (code + runtime): NO. AddQuest refuses completed
    /// non-repeatable quests (CharacterQuests.cs:107-120, QuestDailyLimit).
    /// The daily-reset path (ResetDailyQuests) only clears QuestDetail
    /// Daily/DailyGroup/DailyHunt/DailyLivelihood (7/9/10/11) — cat-34 quests
    /// carry detail_id=6 (Task), so they are NEVER cleared: re-accept is
    /// impossible even across days. => quest-cycle limited to the 88
    /// REPEATABLE='t' quests; cat-34 falls back to character-cycle.
    /// </summary>
    [Test]
    public async Task ReacceptGate_NonRepeatableDaily_Cat34_RefusedEvenAfterDailyReset()
    {
        PlayerbotPilotRig.SeedPilotSingletons();
        var (bot, session) = NewBot("gate-bot");

        // Quest 1959's Start component carries a REAL unit requirement:
        // CompleteQuestContext(1958) — the cat-34 board's predecessor. A real
        // character that sees this quest has 1958 in their completed flags;
        // rig it through the engine's own flag API (the same method the
        // completion path calls, CharacterQuests.SetCompletedQuestFlag).
        bot.Character.Quests.SetCompletedQuestFlag(1958, true);

        var manifest = LoadManifest("t4", 1959); // cat-34 daily (REPEATABLE='f', detail_id=6)
        var result = PlayerbotQuestDriver.DriveQuest(bot, session, manifest, 1);
        await Assert.That(result.Passed, result.ReproTrace()).IsTrue();
        await Assert.That(bot.HasCompleted(1959), "quest 1959 must be completed by the drive").IsTrue();

        // Same-day re-accept: refused by the engine gate.
        var reAccept = bot.AcceptQuest(1959, QuestAcceptorType.Item, 8017);
        await Assert.That(reAccept, "engine MUST refuse re-accept of completed REPEATABLE='f' quest (QuestDailyLimit)").IsFalse();

        // Daily-reset path: cat-34 detail_id=6 is Task, NOT in the daily family
        // (Daily=7/DailyGroup=9/DailyHunt=10/DailyLivelihood=11) -> reset does not
        // clear it -> still refused.
        bot.Character.LeaveTime = DateTime.UtcNow.AddDays(-2);
        bot.Character.Quests.CheckDailyResetAtLogin();
        await Assert.That(bot.HasCompleted(1959),
            "cat-34 (detail Task=6) completed flag must SURVIVE the daily reset — detail not in daily family").IsTrue();
        var reAcceptAfterReset = bot.AcceptQuest(1959, QuestAcceptorType.Item, 8017);
        await Assert.That(reAcceptAfterReset,
            "cat-34 quest-cycle is impossible: re-accept must still be refused after the daily reset").IsFalse();
    }

    /// <summary>
    /// Quest-cycle mode (REPEATABLE='t'): same character re-accepts a completed
    /// quest — 10 cycles on quest 5059 (Solzreed's only REPEATABLE='t' quest).
    /// </summary>
    [Test]
    public async Task QuestCycle_RepeatableQuest_SameCharacterTenCycles()
    {
        PlayerbotPilotRig.SeedPilotSingletons();
        var (bot, session) = NewBot("cycle-bot");
        var manifest = LoadManifest("t1", 5059);

        // 5059 is the jury-point daily: its Start component carries REAL unit
        // requirements — CompleteQuestContext(4784) + MotherFaction(148) +
        // CrimeRecord(1..9) + JuryPoint(>=1). A real level-45 jury-eligible
        // Nuian has all of these; rig through the engine's own surfaces (the
        // completed-flag API the completion path uses + ordinary character
        // fields). The MotherFaction gate dereferences Faction.MotherId —
        // HeadlessSession now seeds the Nuian faction (148) by default.
        bot.Character.Quests.SetCompletedQuestFlag(4784, true);
        bot.Character.JuryPoint = 1;

        var passed = 0;
        var failures = new List<string>();
        for (var cycle = 1; cycle <= 10; cycle++)
        {
            // Level gate re-evaluation per cycle (fresh accept).
            var result = PlayerbotQuestDriver.DriveQuest(bot, session, manifest, (byte)manifest.Template.Level);
            if (!result.Passed)
            {
                failures.Add($"cycle {cycle}: " + result.ReproTrace());
                break;
            }

            // State-cleanup: quest dropped from ActiveQuests, completed flag set once.
            await Assert.That(bot.IsActive(5059), $"cycle {cycle}: quest still active after completion").IsFalse();
            await Assert.That(bot.HasCompleted(5059), $"cycle {cycle}: completed flag missing").IsTrue();
            passed++;
        }

        await Assert.That(failures, "quest-cycle failures: " + string.Join("\n", failures)).IsEmpty();
        await Assert.That(passed, "quest-cycle pass rate must be 10/10").IsEqualTo(10);
        await Assert.That(bot.HasCompleted(5059), "final completed flag").IsTrue();
    }

    #endregion

    #region Character-cycle pilot (required work item 3)

    /// <summary>
    /// Character-cycle mode: 3 bots x 10 cycles through the Solzreed golden
    /// route, fresh headless character per cycle, real gates enforced
    /// (level + kind-31 chains + race). Emits the M2b metrics table.
    /// </summary>
    [Test]
    public async Task CharacterCycle_GoldenRoute_ThreeBots_TenCycles()
    {
        PlayerbotPilotRig.SeedPilotSingletons();
        var run = new PilotRun();
        var manifests = GoldenRoute.ToDictionary(q => q, q => LoadManifest("t1", q));

        for (var botId = 1; botId <= 3; botId++)
        {
            for (var cycle = 1; cycle <= 10; cycle++)
            {
                var (bot, session) = NewBot($"bot{botId}-c{cycle}");

                var leaks = new List<string>();
                var passedQuests = 0;
                var cyclePassed = true;

                foreach (var questId in GoldenRoute)
                {
                    var manifest = manifests[questId];
                    var level = (byte)Math.Max(bot.Character.Level, manifest.Template.Level);
                    var result = PlayerbotQuestDriver.DriveQuest(bot, session, manifest, level);
                    if (!result.Passed)
                    {
                        run.Failures.Add($"bot {botId} cycle {cycle}: " + result.ReproTrace());
                        cyclePassed = false;
                        break;
                    }
                    passedQuests++;
                }

                // State-cleanup checks (M2b table): 0 leaks.
                if (bot.Character.Quests.ActiveQuests.Count != 0)
                    leaks.Add($"ActiveQuests not empty ({bot.Character.Quests.ActiveQuests.Count} quests)");

                // Completed flags: every route quest completed exactly once.
                foreach (var questId in GoldenRoute)
                {
                    if (!bot.HasCompleted(questId))
                        leaks.Add($"completed flag missing for quest {questId}");
                }

                // Reward totals: the manifest's last stage expects exact inventory counts.
                foreach (var questId in GoldenRoute)
                {
                    var manifest = manifests[questId];
                    var lastStage = manifest.Stages.LastOrDefault(s => s.Expect?.RewardItems is { Count: > 0 });
                    if (lastStage?.Expect?.RewardItems != null)
                    {
                        foreach (var rewardItem in lastStage.Expect.RewardItems)
                        {
                            var found = bot.InventoryCount(rewardItem.ItemId);
                            if (found < rewardItem.Count)
                                leaks.Add($"reward total mismatch for quest {questId}: item {rewardItem.ItemId} expected >= {rewardItem.Count}, found {found}");
                        }
                    }
                }

                run.Cycles.Add(new CycleMetrics(botId, cycle, passedQuests, GoldenRoute.Length,
                    cyclePassed && leaks.Count == 0, leaks));
            }
        }

        EmitMetricsTable(run, "Solzreed golden route (character-cycle)");

        // Drift detection: no silent failures.
        await Assert.That(run.Failures,
            "DRIFT DETECTED — regression cards required:\n" + string.Join("\n", run.Failures)).IsEmpty();

        // Cycle pass rate green bar: 100% (10/10) per bot.
        foreach (var botGroup in run.Cycles.GroupBy(c => c.Bot))
        {
            var passed = botGroup.Count(c => c.Passed);
            await Assert.That(passed, $"bot {botGroup.Key} pass rate must be 10/10").IsEqualTo(10);
        }

        // Mean cycles-to-complete stable within ±1 over the last 5 cycles.
        var last5 = run.Cycles.OrderByDescending(c => (c.Bot, c.Cycle)).Take(15);
        var mean = last5.Average(c => c.Passed ? 1 : 0);
        await Assert.That(mean,
            "deterministic drive must complete in 1 cycle (mean cycles-to-complete = 1.0)").IsEqualTo(1.0);

        // State-cleanup green bar: 0 leaks over the run.
        await Assert.That(run.Cycles.Sum(c => c.CleanupLeaks.Count),
            "state-cleanup leaks: " + string.Join("; ", run.Cycles.SelectMany(c => c.CleanupLeaks).Distinct())).IsEqualTo(0);
    }

    #endregion

    #region Restart persistence + cross-cycle isolation (required work item 4)

    /// <summary>
    /// Restart persistence: mid-quest disconnect -> reconnect (fresh session,
    /// quest state restored via the engine's ReadData path) must resume
    /// without duplication or loss. Full-state match on 2 checkpoints.
    ///
    /// Checkpoint design: each checkpoint quest (254, 266) is prepared
    /// mid-flight — accepted + progressed to Ready but NOT turned in — because
    /// that is the state a disconnect must survive. Completed route quests
    /// drop out of ActiveQuests (engine terminal state), so checkpointing
    /// between quests would snapshot nothing.
    /// </summary>
    [Test]
    public async Task RestartPersistence_TwoCheckpoints_FullStateMatch()
    {
        PlayerbotPilotRig.SeedPilotSingletons();
        var manifests = GoldenRoute.ToDictionary(q => q, q => LoadManifest("t1", q));

        var checkpoints = new uint[] { 254, 266 }; // mid-chain, both have a real Progress step
        foreach (var checkpointQuest in checkpoints)
        {
            // Drive everything BEFORE the checkpoint to completion on the live bot.
            var (bot, session) = NewBot($"restart-{checkpointQuest}");
            foreach (var questId in GoldenRoute)
            {
                if (questId == checkpointQuest)
                    break;
                var manifest = manifests[questId];
                var level = (byte)Math.Max(bot.Character.Level, manifest.Template.Level);
                var result = PlayerbotQuestDriver.DriveQuest(bot, session, manifest, level);
                await Assert.That(result.Passed, "pre-checkpoint drive failed: " + result.ReproTrace()).IsTrue();
            }

            // Prepare the checkpoint quest mid-flight (accepted + progressed,
            // not turned in) — the state a disconnect must survive. The exact
            // step differs per quest shape (254 has no Progress component and
            // rests at Ready; 266's objective-satisfied Progress rests at
            // Progress/Ready) — what matters is it is ACTIVE and not complete,
            // so there is real state to snapshot.
            var cpManifest = manifests[checkpointQuest];
            var cpLevel = (byte)Math.Max(bot.Character.Level, cpManifest.Template.Level);
            var prepared = PlayerbotQuestDriver.PrepareQuest(bot, session, cpManifest, cpLevel);
            await Assert.That(prepared, $"checkpoint {checkpointQuest}: quest must be active after prepare").IsNotNull();
            await Assert.That(bot.HasCompleted(checkpointQuest),
                $"checkpoint {checkpointQuest}: prepared quest must NOT be completed").IsFalse();

            // Snapshot all active quest state (the "save").
            var snapshot = bot.Character.Quests.ActiveQuests.Values
                .Select(q => new { q.TemplateId, Data = q.WriteData(), Step = q.Step, Status = q.Status })
                .ToList();
            await Assert.That(snapshot.Count,
                $"checkpoint {checkpointQuest}: expected active quests to snapshot").IsGreaterThan(0);

            // "Restart": fresh session, restore via the engine's load path
            // (same as CharacterQuests.Load: new Quest(template, owner) + ReadData).
            var (restartBot, restartSession) = NewBot($"restarted-{checkpointQuest}");
            foreach (var entry in snapshot)
            {
                var template = AAEmu.Game.Core.Managers.QuestManager.Instance.GetTemplate(entry.TemplateId);
                var restored = new Quest(template, restartBot.Character);
                restored.Id = entry.TemplateId;
                restored.TemplateId = entry.TemplateId;
                restored.Status = entry.Status;
                restored.ReadData(entry.Data);
                restartBot.Character.Quests.ActiveQuests.Add(entry.TemplateId, restored);
                restored.QuestInitialized();
                restored.RequestEvaluation();
            }

            // Full-state match: byte-identical re-serialization + step/status equality.
            var restartState = restartBot.Character.Quests.ActiveQuests.Values
                .Select(q => new { q.TemplateId, Data = q.WriteData(), Step = q.Step, Status = q.Status })
                .ToList();

            await Assert.That(restartState.Count,
                $"checkpoint {checkpointQuest}: active quest count changed after restart").IsEqualTo(snapshot.Count);
            foreach (var entry in snapshot)
            {
                var restored = restartState.FirstOrDefault(r => r.TemplateId == entry.TemplateId);
                await Assert.That(restored, $"checkpoint {checkpointQuest}: quest {entry.TemplateId} lost on restart").IsNotNull();
                await Assert.That(restored!.Data.SequenceEqual(entry.Data),
                    $"checkpoint {checkpointQuest}: quest {entry.TemplateId} WriteData round-trip byte mismatch (duplication/loss)").IsTrue();
                await Assert.That(restored.Step,
                    $"checkpoint {checkpointQuest}: step drift on quest {entry.TemplateId}").IsEqualTo(entry.Step);
                await Assert.That(restored.Status,
                    $"checkpoint {checkpointQuest}: status drift on quest {entry.TemplateId}").IsEqualTo(entry.Status);
            }

            // No duplication: restarting twice must not duplicate quest rows.
            await Assert.That(restartBot.Character.Quests.ActiveQuests.Count,
                $"checkpoint {checkpointQuest}: restart duplicated active quests").IsEqualTo(snapshot.Count);

            // Resume the prepared quest through the REAL turn-in path on the
            // restarted bot — the reconnect must finish what the disconnect
            // interrupted, with the same reward outcome.
            var resumed = PlayerbotQuestDriver.ResumePreparedQuest(restartBot, restartSession, cpManifest);
            await Assert.That(resumed.Passed,
                $"checkpoint {checkpointQuest}: resume after restart failed: " + resumed.ReproTrace()).IsTrue();
            await Assert.That(restartBot.HasCompleted(checkpointQuest),
                $"checkpoint {checkpointQuest}: completed flag must be set after resume").IsTrue();
            await Assert.That(restartBot.IsActive(checkpointQuest),
                $"checkpoint {checkpointQuest}: quest must drop from ActiveQuests after resume").IsFalse();
        }
    }

    /// <summary>
    /// Cross-cycle isolation: cycle N+1 starts from the same baseline as
    /// cycle 1 — byte-identical start state (no cumulative drift).
    /// </summary>
    [Test]
    public async Task CrossCycleIsolation_BaselineByteIdentical()
    {
        PlayerbotPilotRig.SeedPilotSingletons();

        var baseline = CaptureBaseline(NewBot("baseline").Bot);
        for (var cycle = 2; cycle <= 5; cycle++)
        {
            var (bot, _) = NewBot($"iso-c{cycle}");
            var state = CaptureBaseline(bot);
            await Assert.That(state,
                $"cycle {cycle}: baseline drifted (cross-cycle isolation violated)").IsEqualTo(baseline);
        }
    }

    private static string CaptureBaseline(PlayerBotController bot)
    {
        // Byte-identical start state: no active quests, no completed flags,
        // empty inventory, starting level.
        var sb = new StringBuilder();
        sb.Append("active=").Append(bot.Character.Quests.ActiveQuests.Count).Append(';');
        sb.Append("level=").Append(bot.Character.Level).Append(';');
        sb.Append("inv=").Append(bot.InventoryCount(0)).Append(';');
        var anyCompleted = false;
        for (var i = 0; i < 5000; i += 64)
            anyCompleted |= bot.HasCompleted((uint)i);
        sb.Append("completed=").Append(anyCompleted);
        return sb.ToString();
    }

    #endregion

    #region Seeded-regression proof (required work item 5)

    /// <summary>
    /// Seeded defect: quest 251's report target is wrong (NpcId swapped to a
    /// non-existent NPC). The bot must FAIL the turn-in with a repro trace;
    /// reverting the defect must restore green (fail-before / pass-after at
    /// bot level — the regression-harness contract in action).
    /// </summary>
    [Test]
    public async Task SeededDefect_WrongReportNpc_FailBefore_PassAfter()
    {
        PlayerbotPilotRig.SeedPilotSingletons();
        var manifest = LoadManifest("t1", 251);

        // ---- FAIL-BEFORE: inject the defect into the loaded template ----
        var template = AAEmu.Game.Core.Managers.QuestManager.Instance.GetTemplate(251);
        var reportAct = template.Components.Values
            .SelectMany(c => c.ActTemplates)
            .OfType<AAEmu.Game.Models.Game.Quests.Acts.QuestActConReportNpc>()
            .First();
        var originalNpcId = reportAct.NpcId;
        reportAct.NpcId = 999999; // wrong report target (data-defect class)

        var (bot, session) = NewBot("seeded-fail");
        var failResult = PlayerbotQuestDriver.DriveQuest(bot, session, manifest, 1);
        await Assert.That(failResult.Passed, "seeded defect must FAIL the bot run").IsFalse();
        await Assert.That(failResult.FailStage is "READY" or "REWARD" or "VERIFY",
            "failure must surface at turn-in/completion, got " + failResult.FailStage).IsTrue();
        Console.WriteLine("FAIL-BEFORE repro trace:\n" + failResult.ReproTrace());

        // ---- PASS-AFTER: revert the defect ----
        reportAct.NpcId = originalNpcId;

        var (bot2, session2) = NewBot("seeded-pass");
        var passResult = PlayerbotQuestDriver.DriveQuest(bot2, session2, manifest, 1);
        await Assert.That(passResult.Passed,
            "reverted defect must PASS the bot run: " + passResult.ReproTrace()).IsTrue();
    }

    #endregion
}
