using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using AAEmu.Commons.Utils;
using NLog;

namespace AAEmu.Game.Core.Managers;

/// <summary>
/// Represents a static physical obstacle (fence, wall, gate, building, etc.)
/// extracted from world doodad spawn tables for bot navigation avoidance.
/// </summary>
public sealed record NavObstacle(
    uint TemplateId,
    string Name,
    string Category,
    Vector3 Position,
    float Yaw,
    float Radius
);

/// <summary>
/// Schema mapping for deserializing obstacle catalogs generated by extract_doodad_obstacles.py
/// </summary>
internal sealed class NavObstacleCatalogJson
{
    [JsonPropertyName("zone")]
    public string? Zone { get; set; }

    [JsonPropertyName("totalObstacles")]
    public int TotalObstacles { get; set; }

    [JsonPropertyName("obstacles")]
    public List<NavObstacleEntryJson>? Obstacles { get; set; }
}

internal sealed class NavObstacleEntryJson
{
    [JsonPropertyName("templateId")]
    public uint TemplateId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("category")]
    public string? Category { get; set; }

    [JsonPropertyName("x")]
    public float X { get; set; }

    [JsonPropertyName("y")]
    public float Y { get; set; }

    [JsonPropertyName("z")]
    public float Z { get; set; }

    [JsonPropertyName("yaw")]
    public float Yaw { get; set; }

    [JsonPropertyName("keepOutRadius")]
    public float KeepOutRadius { get; set; }
}

/// <summary>
/// Obstacle avoidance and collision query manager.
/// Indexes world static doodad obstacles into a 2D spatial hash grid for sub-microsecond
/// pathfinding exclusion and raycast line-of-sight checks.
/// </summary>
public class ObstacleManager : Singleton<ObstacleManager>, ILoadable
{
    private static Logger Logger { get; } = LogManager.GetCurrentClassLogger();

    private const float CellSize = 100f;
    private const float VerticalTolerance = 6.0f;

    private readonly object _lock = new();
    private readonly Dictionary<(int CellX, int CellY), List<NavObstacle>> _grid = [];
    private readonly List<NavObstacle> _allObstacles = [];

    public string DataDirectory { get; set; } = Path.Combine("Data", "Navigation");

    public int TotalObstacleCount
    {
        get
        {
            lock (_lock)
            {
                return _allObstacles.Count;
            }
        }
    }

    public void Load()
    {
        lock (_lock)
        {
            _grid.Clear();
            _allObstacles.Clear();

            if (!Directory.Exists(DataDirectory))
            {
                Logger.Info($"[ObstacleManager] Data directory '{DataDirectory}' does not exist. No obstacles loaded.");
                return;
            }

            var files = Directory.GetFiles(DataDirectory, "*_obstacles.json");
            foreach (var file in files)
            {
                LoadObstaclesFromFile(file);
            }

            Logger.Info($"[ObstacleManager] Loaded {_allObstacles.Count} total obstacles across {_grid.Count} spatial cells from {files.Length} catalogs.");
        }
    }

    public void LoadObstaclesFromFile(string filePath)
    {
        try
        {
            var json = File.ReadAllText(filePath);
            var catalog = JsonSerializer.Deserialize<NavObstacleCatalogJson>(json);
            if (catalog?.Obstacles == null)
                return;

            foreach (var o in catalog.Obstacles)
            {
                var radius = o.KeepOutRadius > 0f ? o.KeepOutRadius : 2.0f;
                var pos = new Vector3(o.X, o.Y, o.Z);
                var obstacle = new NavObstacle(
                    o.TemplateId,
                    o.Name ?? "Obstacle",
                    o.Category ?? "structure",
                    pos,
                    o.Yaw,
                    radius
                );

                AddObstacle(obstacle);
            }
        }
        catch (Exception ex)
        {
            Logger.Error(ex, $"[ObstacleManager] Failed to load obstacles from '{filePath}': {ex.Message}");
        }
    }

    public void AddObstacle(NavObstacle obstacle)
    {
        _allObstacles.Add(obstacle);

        var minCellX = (int)MathF.Floor((obstacle.Position.X - obstacle.Radius) / CellSize);
        var maxCellX = (int)MathF.Floor((obstacle.Position.X + obstacle.Radius) / CellSize);
        var minCellY = (int)MathF.Floor((obstacle.Position.Y - obstacle.Radius) / CellSize);
        var maxCellY = (int)MathF.Floor((obstacle.Position.Y + obstacle.Radius) / CellSize);

        for (var cx = minCellX; cx <= maxCellX; cx++)
        {
            for (var cy = minCellY; cy <= maxCellY; cy++)
            {
                var key = (cx, cy);
                if (!_grid.TryGetValue(key, out var list))
                {
                    list = [];
                    _grid[key] = list;
                }
                list.Add(obstacle);
            }
        }
    }

    /// <summary>
    /// Checks if a 3D world position falls inside the keep-out radius of any obstacle.
    /// </summary>
    public bool IsBlocked(Vector3 point, float extraMargin = 0f)
    {
        lock (_lock)
        {
            if (_allObstacles.Count == 0)
                return false;

            var cx = (int)MathF.Floor(point.X / CellSize);
            var cy = (int)MathF.Floor(point.Y / CellSize);

            if (!_grid.TryGetValue((cx, cy), out var obstacles))
                return false;

            foreach (var obs in obstacles)
            {
                if (MathF.Abs(point.Z - obs.Position.Z) > VerticalTolerance)
                    continue;

                var dx = point.X - obs.Position.X;
                var dy = point.Y - obs.Position.Y;
                var r = obs.Radius + extraMargin;

                if (dx * dx + dy * dy <= r * r)
                    return true;
            }

            return false;
        }
    }

    /// <summary>
    /// Checks if a direct 2D line segment between 'from' and 'to' intersects any obstacle cylinder.
    /// Used to prevent bots from walking straight through fences or walls when off navmesh.
    /// </summary>
    public bool IntersectsObstacle(Vector3 from, Vector3 to, float actorRadius = 0.5f)
    {
        lock (_lock)
        {
            if (_allObstacles.Count == 0)
                return false;

            var minX = MathF.Min(from.X, to.X);
            var maxX = MathF.Max(from.X, to.X);
            var minY = MathF.Min(from.Y, to.Y);
            var maxY = MathF.Max(from.Y, to.Y);

            var minCellX = (int)MathF.Floor(minX / CellSize);
            var maxCellX = (int)MathF.Floor(maxX / CellSize);
            var minCellY = (int)MathF.Floor(minY / CellSize);
            var maxCellY = (int)MathF.Floor(maxY / CellSize);

            var tested = new HashSet<NavObstacle>();

            for (var cx = minCellX; cx <= maxCellX; cx++)
            {
                for (var cy = minCellY; cy <= maxCellY; cy++)
                {
                    if (!_grid.TryGetValue((cx, cy), out var obstacles))
                        continue;

                    foreach (var obs in obstacles)
                    {
                        if (!tested.Add(obs))
                            continue;

                        var minZ = MathF.Min(from.Z, to.Z) - VerticalTolerance;
                        var maxZ = MathF.Max(from.Z, to.Z) + VerticalTolerance;
                        if (obs.Position.Z < minZ || obs.Position.Z > maxZ)
                            continue;

                        var effectiveRadius = obs.Radius + actorRadius;
                        if (SegmentIntersectsCircle(from.X, from.Y, to.X, to.Y, obs.Position.X, obs.Position.Y, effectiveRadius))
                            return true;
                    }
                }
            }

            return false;
        }
    }

    /// <summary>
    /// Returns all obstacles within a radius of the given point.
    /// </summary>
    public IReadOnlyList<NavObstacle> GetNearbyObstacles(Vector3 point, float searchRadius)
    {
        lock (_lock)
        {
            if (_allObstacles.Count == 0)
                return [];

            var results = new List<NavObstacle>();
            var minCellX = (int)MathF.Floor((point.X - searchRadius) / CellSize);
            var maxCellX = (int)MathF.Floor((point.X + searchRadius) / CellSize);
            var minCellY = (int)MathF.Floor((point.Y - searchRadius) / CellSize);
            var maxCellY = (int)MathF.Floor((point.Y + searchRadius) / CellSize);

            var seen = new HashSet<NavObstacle>();

            for (var cx = minCellX; cx <= maxCellX; cx++)
            {
                for (var cy = minCellY; cy <= maxCellY; cy++)
                {
                    if (!_grid.TryGetValue((cx, cy), out var obstacles))
                        continue;

                    foreach (var obs in obstacles)
                    {
                        if (!seen.Add(obs))
                            continue;

                        var dx = point.X - obs.Position.X;
                        var dy = point.Y - obs.Position.Y;
                        if (dx * dx + dy * dy <= (searchRadius + obs.Radius) * (searchRadius + obs.Radius))
                        {
                            results.Add(obs);
                        }
                    }
                }
            }

            return results;
        }
    }

    private static bool SegmentIntersectsCircle(float x1, float y1, float x2, float y2, float cx, float cy, float r)
    {
        var dx = x2 - x1;
        var dy = y2 - y1;
        var lenSq = dx * dx + dy * dy;

        if (lenSq < 0.0001f)
        {
            var distSq = (x1 - cx) * (x1 - cx) + (y1 - cy) * (y1 - cy);
            return distSq <= r * r;
        }

        // Project center onto line segment, clamped between 0 and 1
        var t = Math.Clamp(((cx - x1) * dx + (cy - y1) * dy) / lenSq, 0f, 1f);
        var projX = x1 + t * dx;
        var projY = y1 + t * dy;

        var dProjSq = (projX - cx) * (projX - cx) + (projY - cy) * (projY - cy);
        return dProjSq <= r * r;
    }
}
