// <auto-generated />
// Sit-pose fallback table — generated from the 1.2 client (r208022) game_pak census
// (see scorecard-explorations/npc-behavior.md, Recon B, sit-pose section, and bugs/013-npc-sit-pose.md).
//
// WHY: npc_postures.anim_action_id is sent verbatim, but the 1.2 client only ships the
// fist_pos_sit_* .caf assets for a subset of race/gender models (and some sit anim ids,
// e.g. 70/160, have no assets at all). The client cannot play a missing animation and
// falls back to its default crouched pose ("knees in"). This table remaps an unplayable
// sit-range anim id to the closest playable sit anim for the NPC's (race, gender), so the
// client renders a correct sitting pose. Stand/walk poses are NOT in this table.
//
// Generation: Tools/sit-pose-census/sit-pose-census.py <game_pak> <compact.sqlite3> <out.cs>

using AAEmu.Game.Models.Game.Char;

namespace AAEmu.Game.Models.Game.Units;

/// <summary>
/// Remaps NPC sit-pose anim ids that the 1.2 client cannot play for the NPC's (race, gender)
/// to the closest playable sit anim. Only the sit range (ids 25-224) is covered.
/// </summary>
public static class SitPoseFallback
{
    /// <summary>Anim action ids in the sit-pose range this table may remap (inclusive).</summary>
    public const uint SitRangeMin = 25;
    public const uint SitRangeMax = 224;

    // (animActionId, folderIndex, gender) -> fallback animActionId
    // folderIndex: 1=nuian, 2=dwarf, 3=hariharan(elf), 4=ferre, 5=warborn
    private static readonly Dictionary<(uint, byte, byte), uint> Fallbacks = new()
    {
        [(25, 3, 1)] = 224,
        [(25, 3, 2)] = 223,
        [(26, 3, 1)] = 141,
        [(26, 3, 2)] = 141,
        [(27, 1, 2)] = 141,
        [(27, 3, 1)] = 141,
        [(27, 3, 2)] = 141,
        [(27, 4, 2)] = 141,
        [(53, 1, 2)] = 141,
        [(53, 3, 2)] = 141,
        [(53, 4, 2)] = 141,
        [(56, 1, 2)] = 141,
        [(56, 3, 1)] = 141,
        [(56, 3, 2)] = 141,
        [(56, 4, 2)] = 141,
        [(59, 1, 1)] = 224,
        [(59, 1, 2)] = 223,
        [(59, 2, 1)] = 224,
        [(59, 3, 1)] = 224,
        [(59, 3, 2)] = 223,
        [(59, 4, 1)] = 224,
        [(59, 4, 2)] = 223,
        [(59, 5, 1)] = 224,
        [(61, 1, 1)] = 224,
        [(61, 1, 2)] = 223,
        [(61, 2, 1)] = 224,
        [(61, 3, 1)] = 224,
        [(61, 3, 2)] = 223,
        [(61, 4, 1)] = 224,
        [(61, 4, 2)] = 223,
        [(61, 5, 1)] = 224,
        [(62, 1, 1)] = 224,
        [(62, 1, 2)] = 223,
        [(62, 2, 1)] = 224,
        [(62, 3, 1)] = 224,
        [(62, 3, 2)] = 223,
        [(62, 4, 1)] = 224,
        [(62, 4, 2)] = 223,
        [(62, 5, 1)] = 224,
        [(63, 1, 1)] = 224,
        [(63, 1, 2)] = 223,
        [(63, 2, 1)] = 224,
        [(63, 3, 1)] = 224,
        [(63, 3, 2)] = 223,
        [(63, 4, 1)] = 224,
        [(63, 4, 2)] = 223,
        [(63, 5, 1)] = 224,
        [(65, 1, 2)] = 155,
        [(65, 3, 1)] = 141,
        [(65, 3, 2)] = 141,
        [(65, 4, 2)] = 155,
        [(70, 1, 1)] = 224,
        [(70, 1, 2)] = 223,
        [(70, 2, 1)] = 224,
        [(70, 3, 1)] = 224,
        [(70, 3, 2)] = 223,
        [(70, 4, 1)] = 224,
        [(70, 4, 2)] = 223,
        [(70, 5, 1)] = 224,
        [(71, 1, 2)] = 141,
        [(71, 3, 2)] = 141,
        [(71, 4, 2)] = 141,
        [(75, 1, 2)] = 223,
        [(75, 3, 1)] = 224,
        [(75, 3, 2)] = 223,
        [(75, 4, 1)] = 224,
        [(75, 4, 2)] = 223,
        [(81, 3, 1)] = 141,
        [(81, 3, 2)] = 141,
        [(87, 1, 2)] = 141,
        [(87, 3, 2)] = 141,
        [(87, 4, 2)] = 141,
        [(92, 1, 2)] = 141,
        [(92, 3, 2)] = 141,
        [(92, 4, 2)] = 141,
        [(93, 1, 2)] = 141,
        [(93, 3, 2)] = 141,
        [(93, 4, 2)] = 141,
        [(94, 1, 1)] = 141,
        [(94, 1, 2)] = 141,
        [(94, 3, 1)] = 141,
        [(94, 3, 2)] = 141,
        [(94, 4, 1)] = 141,
        [(94, 4, 2)] = 141,
        [(94, 5, 1)] = 141,
        [(96, 1, 2)] = 141,
        [(96, 3, 2)] = 141,
        [(96, 4, 2)] = 141,
        [(105, 1, 1)] = 141,
        [(105, 2, 1)] = 141,
        [(105, 3, 1)] = 141,
        [(105, 4, 1)] = 141,
        [(105, 5, 1)] = 141,
        [(115, 1, 2)] = 141,
        [(115, 2, 1)] = 141,
        [(115, 3, 2)] = 141,
        [(115, 4, 1)] = 141,
        [(115, 4, 2)] = 141,
        [(124, 1, 1)] = 141,
        [(124, 1, 2)] = 141,
        [(124, 2, 1)] = 141,
        [(124, 3, 1)] = 141,
        [(124, 3, 2)] = 141,
        [(124, 4, 1)] = 141,
        [(124, 4, 2)] = 141,
        [(124, 5, 1)] = 141,
        [(142, 1, 1)] = 224,
        [(142, 1, 2)] = 223,
        [(142, 2, 1)] = 224,
        [(142, 3, 1)] = 224,
        [(142, 3, 2)] = 223,
        [(142, 4, 1)] = 224,
        [(142, 4, 2)] = 223,
        [(142, 5, 1)] = 224,
        [(144, 1, 1)] = 141,
        [(144, 2, 1)] = 141,
        [(144, 3, 1)] = 141,
        [(144, 4, 1)] = 141,
        [(144, 5, 1)] = 141,
        [(155, 3, 1)] = 141,
        [(155, 3, 2)] = 141,
        [(159, 1, 1)] = 141,
        [(159, 1, 2)] = 141,
        [(159, 2, 1)] = 141,
        [(159, 3, 1)] = 141,
        [(159, 3, 2)] = 141,
        [(159, 4, 1)] = 141,
        [(159, 4, 2)] = 141,
        [(159, 5, 1)] = 141,
        [(160, 1, 1)] = 141,
        [(160, 1, 2)] = 141,
        [(160, 2, 1)] = 141,
        [(160, 3, 1)] = 141,
        [(160, 3, 2)] = 141,
        [(160, 4, 1)] = 141,
        [(160, 4, 2)] = 141,
        [(160, 5, 1)] = 141,
        [(174, 3, 1)] = 141,
        [(174, 3, 2)] = 141,
        [(186, 1, 2)] = 141,
        [(186, 3, 1)] = 141,
        [(186, 3, 2)] = 141,
        [(186, 4, 2)] = 141,
        [(187, 1, 1)] = 141,
        [(187, 1, 2)] = 141,
        [(187, 2, 1)] = 141,
        [(187, 3, 1)] = 141,
        [(187, 3, 2)] = 141,
        [(187, 4, 1)] = 141,
        [(187, 4, 2)] = 141,
        [(187, 5, 1)] = 141,
        [(199, 3, 1)] = 141,
        [(199, 3, 2)] = 141,
        [(201, 1, 2)] = 155,
        [(201, 3, 1)] = 141,
        [(201, 3, 2)] = 141,
        [(201, 4, 1)] = 155,
        [(201, 4, 2)] = 155,
        [(208, 1, 1)] = 224,
        [(208, 1, 2)] = 223,
        [(208, 2, 1)] = 224,
        [(208, 3, 1)] = 224,
        [(208, 3, 2)] = 223,
        [(208, 4, 1)] = 224,
        [(208, 4, 2)] = 223,
        [(208, 5, 1)] = 224,
        [(216, 1, 1)] = 141,
        [(216, 2, 1)] = 141,
        [(216, 3, 1)] = 141,
        [(216, 4, 1)] = 141,
        [(216, 5, 1)] = 141,
        [(223, 1, 1)] = 224,
        [(223, 3, 1)] = 224,
        [(223, 4, 1)] = 224,
        [(223, 5, 1)] = 224,
        [(224, 1, 2)] = 223,
        [(224, 3, 2)] = 223,
        [(224, 4, 2)] = 223,
    };

    /// <summary>
    /// Returns the playable fallback for <paramref name="animActionId"/> on the given race/gender,
    /// or the original id when it is playable, out of the sit range, or has no known fallback.
    /// </summary>
    public static uint Resolve(uint animActionId, byte race, byte gender)
    {
        if (animActionId < SitRangeMin || animActionId > SitRangeMax)
            return animActionId; // stand/walk/other poses pass through untouched

        var folder = FolderIndex((Race)race);
        if (folder == 0)
            return animActionId;

        return Fallbacks.GetValueOrDefault((animActionId, folder, gender), animActionId);
    }

    /// <summary>Maps a Race to the client animation folder index (1=nuian, 2=dwarf, 3=hariharan, 4=ferre, 5=warborn). 0 = unknown.</summary>
    private static byte FolderIndex(Race race) => race switch
    {
        Race.Nuian or Race.Fairy or Race.Returned => 1,
        Race.Dwarf => 2,
        Race.Elf or Race.Hariharan => 3,
        Race.Ferre => 4,
        Race.Warborn => 5,
        _ => 0,
    };
}
